language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean  source:jar deploy javadoc:javadoc --settings travis_settings.xml

# travis encrypt -r nhl/bootique-tapestry "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r nhl/bootique-tapestry "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "Nc+fsUctNWKjGStWrA1ulBQXfr+7gXagkbmRdHAHvrBxRdsUM6WJ3jFzkarHd5Da9R6lLQpr2reNfwKtGzBtkfQYgaleZ7DIDDHcjhV8mKjDt62tM+efBDc01/eKKMJnd4CE/HxUjt/+R5s4CDahR4fvKR1pUCiNjTDz0L4HqBnXYsG/CvCOkcnk7vVn7kqNyYxBJMMd4GJHG2Vh1S26EDIpljzUq+8syRnS30y8jcHPJALUqhMn+8Ukb+Gn7ZvafJ4OqlxGT8/petg6FC4jrg3yKPkN9Y8V/LFwgrrGLCKawieXIFRsLXdw2ulYSm0nFnQ/wHfVc6+ZvXV/QiClDZJ6Y9TYoOdqr+l78calmrmGhb3M9AK8ee9d/Y4f9xzUQjHgADszY6/8aYBu0Q7yRNZK0VdeNxt3Vg4NjUF0z9gtdIUgn1bZlu/js+GPv3+xKd0LEn+2yGhiwg8zk7j9iftLqngtCHmVyYrQcb2F57Jm7+qBOuhb2IT3XvQlpyhp4l1sKvJbFLyk2z3SoNido0u8SsBwDaaM1BdOk6SxMKQhcwjPXV8KOg59kt+BFBsA4QRisYtvJajb/0dz14vfl17k3QWylfrbJVCFEt2xLZEeeFN6yBhaLfdI03xEUHOOSHzRe0xAFzKtGLOTi5bKYGM6aZccEuTQ318RHXKz+yA="
    - secure: "Gh1dOv4QXNAyzdZpKJ2sQgoPw25zLcXUv3Cn6XIM/1SkZ1aVdzU9vai6Tk8ptuT0Z69EVqIkz2s6n2cb51OS8UpW105d6I697uJLUOGIj1lopSGAlgiX6qRW493SqOKhLIKDF89/o4Pzvt/0wiw3tk/rg4Cl9YBwnUhFRRVB/M6J04Jhz/aT9mk3jEbCPcrqkRQ/T1OieW+XfEQsmeSzozKYqqUBCwz2pfarcg74zPtO6s4+yorj8bbuphU2COyq8bVGPHd/1exHLeFq4DYcoDrCoKgwpYiQxAHqeGqYfbxB+Z/irrFpS0g/Y4hBwrvaulpZOKCU3daY5JfKATBNYoQ/bXeJkkCFPOvnaHpovanY3tf8OVIx113Dg7WZcsdIhIDUoXzv3USIm17heoe7ic+lxPW5zAshmxw7jjO93ts5B6SpeZZRNdQVJbPYVnKHVMYxF6GelnI85eJGHuA1zvWxyJuPC6MSugaqylaGkXhbBnYDp+XqMigiVKCpmr8aVkvwf2Z7PtvE4z7r/zdQdm2uKR1e2nZZEUvhychhV/T43W2TFRUphaWvAVKaNk1n1DLwI/dyjgTQrSKTvWbHumXlmVPg6M5vNc++mbvxLrhTYR4oc7I+fRK/QaPKVTTAnKXK6Q/qw/JK30G/hQtrjQtonHn/2zM+kR+jV8pDjtg="
