language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean  source:jar deploy javadoc:javadoc --settings travis_settings.xml

# travis encrypt -r nhl/bootique-tapestry "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r nhl/bootique-tapestry "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "dypvXb3ZJH2n93lFAG9DGQ7BgTJu41XwAevNyCj2kVumsBVxKNVHkoV3nSDjHK6d/Aok1qjCXSBnq6dnEBv6nHr/O9XB5rNfcjHyDw/0QAXKu9LrOeEk1z8eU/dd5SkUsTnodVihq6kvNUn2uPezLm0RWEktVsXBkgEhoeL0qxDVSMip+41bS55ROkItsoi3SJzvA/KNBxBdUGEmtJaujatlZIXOTvdJD0vFq0CuGmPU3t9dz4pTA8kyHhJIDoDsAjeVETd4PHgzOEmscVc8DgrczpMP4jNENSnbwrCkkQSCqp5R8srsxIPOmNuh0e89yvef+MVbmlIYSDsKqrJJAHbwD7YjU0k0ESGdaWiJMuXSvTRbRYtkhLHNtQH4yBmfiY6Nttrh1dSdV50aYyHc060G55wAMWglD+W+xMvO+M8ceTUgegvTqMYUoZUEO0Tj2mJK3+3u/fIbP1xucbzJ5lXx55ubU0KDTod80Qd91btAPylyN0PaYrDVyQ7rkGBzluuvk4Nwtg2qLOC6LqIoY7VN7ic2qXNigNnqrIjGk6k3/eEAvGE2uwYV4HMNMfGXoQsexITL9lT8P34M5pgIz6lEL6a/EQYCOD+7Obj5GTQmyk2t9N4YygKGTc6zrKkonsUNsSRY5lBl4YqtLB4IIKD64cnvW0tsh5eMOHMsWxw="
    - secure: "fp4D9U4Wrhx0FOqtTKRnDRZgvD5ZU2RHJBYbWOR9Dt2oLUpPcNUEMB5devFhnyi7vPTgTGCBqxJ/Ro1VG8eFG13E1TnLNqu9dbfdekhC++yC9b6cfPw8Cwryt2qMLIkB/cE8z5gctQq3tmq36YJKBYs4IsMo4fN63w7uQCDgULPxY/egp8RNZlkhMAF39697i/kWyBeQz/HBz00ZNLm8bHgZCV5WB9WnVuVABM8GQysPLZqVD11eJQVl5KeBWKeIhG25jcFO5YZU3vmpcNmfup2OT2i4AdW5su/UjjBUb5KIGIsbXHnQ9R4X0BvqDVuRGgeLzsCQBVpBjZBZHZafbKRoRArpaC/Ia99qnXHA6hm3zzCxjBZZqd8QBYy88fglHh1XFxjWGWMK7cb6y8M0X3r6l2toX03yef2Ri0r8bHRYrUSgMehC1Xp2iC78slQDE5jmcdlXm7gZ1Zb+qPE8tc6fVoU4Hpsx69Qqj0N9pXrObTMJWyDPlFYl9Cviea/DPtutWGpIvm+Sh5u/QJjriUC0nEMHcOX/OOnA+4jF8oGrhaEoL/60hntt9kFHoGDBiCH0VX5BoKwVGbns1msKAS5aBleGnwGka8nb+IV7u6mYHCZVJXIMXHT/0VON4cOCSZ0ltimksmCvJik9cywsJFAWB5nnSHybYexFnotnwc4="
